HomeWork02-01
MastersAcademy/ruby-course-2020 pull request #28
Opened 2020-11-02 23:32 UTC by AndSaf1

2020-11-03 07:32 UTC, alexgonor requested changes

2020-11-03 07:32 UTC, alexgonor commented on andriy.safronov/03.rb
> +    end
there should be empty line between methods

2020-11-03 07:32 UTC, alexgonor commented on andriy.safronov/03.rb
> +        "Поїсти: #{@eat_time}, Попити: #{@drink_time}, Спати: #{@sleep_time}"
please, write only in english

2020-11-03 07:32 UTC, alexgonor commented on andriy.safronov/03.rb
> +        @eat_time = 8
indent should be two spaces. You can read this ruby style guide https://github.com/github/rubocop-github/blob/master/STYLEGUIDE.md

2020-11-03 07:32 UTC, alexgonor commented on andriy.safronov/03.rb
> +me = Tamagochi.new
variable naming confuse, I think maybe you need to create some kind of animal, but not you as an object of tamagochi

2020-11-03 07:32 UTC, alexgonor commented on andriy.safronov/03.rb
> +    @sleep_time += 1
please, adjust spaces and indents all over this class

2020-11-03 20:36 UTC, alexgonor approved these changes

2020-11-03 20:42 UTC, alexgonor commented
Also, you need to do the second task with brackets validation
Задача 2 Є чотири види дужок - ‘{’ ‘[’ ‘(’ ‘<’ Для кожної з них є відповідна закриваюча дужка - ‘}’ ‘]’ ‘)’ ‘>’
Розширити класс String методом valid? для перевірки строки яка складається лише з дужок на валідність
“{(})“.valid? => false
“{{[]“.valid? => false
“{[()]}“.valid? => true

2020-11-03 22:27 UTC, AndSaf1 commented
Sorry. It is too difficult for me. I can't understand the algorithms

2020-11-03 22:28 UTC, AndSaf1 commented
What do you advise to read ...

2020-11-04 07:38 UTC, alexgonor commented
The most suitable that I found for this task: https://rubyrush.ru/steps/loops.html
But the main idea for this task create logical algorithm how it could be done and decompose task to many small tasks and solving these small tasks, for example:
1. Take string of brackets and separate it to array
2. We know that it should be open bracket at the start and closed at the end. So, we can take first and last array elements and compare them, if they equal then we can took next pair after first and last.
3. And so on...

2020-11-04 16:23 UTC, merged